services:
  server:
    build: ./server
    command: ["bash", "run-opt-1.3b.sh"]
    restart: unless-stopped
    volumes:
      - ./server:/app/server
      - ./client/dist:/app/client/dist
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  client:
    image: node:20-alpine
    working_dir: /app/client
    command: ["sh", "-c", "npm install && npm run build"]
    volumes:
      - ./client:/app/client
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
