name: spirit-box
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip<24.1
  - pytorch=2.4
  - torchvision=0.19
  - torchaudio=2.4
  - pytorch-cuda=12.4
  - pip:
      - python-dotenv==1.0.1
      - click==8.1.7
      - audiolm-pytorch==1.1.4
      - sentencepiece==0.2.0
      - fairseq==0.12.2
      - huggingface-hub==0.25.0
      - transformers==4.43.4
      - encodec==0.1.1
      - wtpsplit==2.0.8
      - scipy==1.14.1
      - optimum==1.22.0
      - pydub==0.25.1
      # socketio
      - python-socketio==5.11.4
      - eventlet==0.36.1
